version: '3'

networks:
  app-tracker:
    driver: bridge

services:
  backend-app-tracker:
    image: job-app-tracker
    build:
      context: ./backend
    volumes:
      - ../backend:/backend
      - ../.env:/backend/.env
    container_name: job-app-tracker
    working_dir: /backend
    ports:
      - 3000:3000
    tty: true
    networks:
      - app-tracker

  postgres-app-tracker:
    image: postgres-app-tracker
    build:
        context: ./postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    container_name: postgres-app-tracker
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
    - 5432:5432
    networks:
      - app-tracker
